version: '3' # version of docker-compose
services:
  www:
    image: php:apache # image to use
    volumes:
      - "./:/var/www/html" # mount the current directory to /var/www/html
    ports:  # expose ports
      - "80:80"
      - 443:443 # furture ssl traffic
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: php_docker
      MYSQL_USER: php_docker
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './db:/docker-entrypoint-initdb.d'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306